/*
 * generated by Xtext 2.12.0
 */
package championsProject.parser.antlr;

import championsProject.parser.antlr.internal.InternalXTextParser;
import championsProject.services.XTextGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class XTextParser extends AbstractAntlrParser {

	@Inject
	private XTextGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalXTextParser createParser(XtextTokenStream stream) {
		return new InternalXTextParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Fifa";
	}

	public XTextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(XTextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
