/*
 * generated by Xtext 2.12.0
 */
package championsProject.ui.tests;

import championsProject.XText.ui.internal.XTextActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class XTextUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XTextActivator.getInstance().getInjector("championsProject.XText");
	}

}
