/*
 * generated by Xtext 2.12.0
 */
package championsProject


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class XTextStandaloneSetup extends XTextStandaloneSetupGenerated {

	def static void doSetup() {
		new XTextStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
