/**
 * generated by Xtext 2.12.0
 */
package championsProject.ide;

import championsProject.XTextRuntimeModule;
import championsProject.XTextStandaloneSetup;
import championsProject.ide.XTextIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class XTextIdeSetup extends XTextStandaloneSetup {
  @Override
  public Injector createInjector() {
    XTextRuntimeModule _xTextRuntimeModule = new XTextRuntimeModule();
    XTextIdeModule _xTextIdeModule = new XTextIdeModule();
    return Guice.createInjector(Modules2.mixin(_xTextRuntimeModule, _xTextIdeModule));
  }
}
