/**
 * generated by Xtext 2.12.0
 */
package championsProject.ide;

import championsProject.ide.AbstractXTextIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class XTextIdeModule extends AbstractXTextIdeModule {
}
