/*
 * generated by Xtext 2.12.0
 */
package championsProject.ui;

import championsProject.XText.ui.internal.XTextActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XTextExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XTextActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XTextActivator.getInstance().getInjector(XTextActivator.CHAMPIONSPROJECT_XTEXT);
	}
	
}
