/*
 * generated by Xtext 2.12.0
 */
package championsProject.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractXTextScopeProvider extends DelegatingScopeProvider {
}
