/**
 * generated by Xtext 2.12.0
 */
package championsProject.ui.contentassist;

import championsProject.ui.contentassist.AbstractXTextProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class XTextProposalProvider extends AbstractXTextProposalProvider {
}
