/**
 * generated by Xtext 2.12.0
 */
package championsProject.validation;

import championsProject.validation.AbstractXTextValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class XTextValidator extends AbstractXTextValidator {
}
