/**
 * generated by Xtext 2.12.0
 */
package championsProject;

import championsProject.AbstractXTextRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class XTextRuntimeModule extends AbstractXTextRuntimeModule {
}
