/**
 * generated by Xtext 2.12.0
 */
package championsProject;

import championsProject.XTextStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class XTextStandaloneSetup extends XTextStandaloneSetupGenerated {
  public static void doSetup() {
    new XTextStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
