/*
 * generated by Xtext 2.12.0
 */
package championsProject.ide.contentassist.antlr;

import championsProject.ide.contentassist.antlr.internal.InternalXTextParser;
import championsProject.services.XTextGrammarAccess;
import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class XTextParser extends AbstractContentAssistParser {

	@Inject
	private XTextGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalXTextParser createParser() {
		InternalXTextParser result = new InternalXTextParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getPersonAccess().getAlternatives(), "rule__Person__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getCompetitionTypeAccess().getAlternatives(), "rule__CompetitionType__Alternatives");
					put(grammarAccess.getTeamTypeAccess().getAlternatives(), "rule__TeamType__Alternatives");
					put(grammarAccess.getPlayerPositionAccess().getAlternatives(), "rule__PlayerPosition__Alternatives");
					put(grammarAccess.getPlayerStatusAccess().getAlternatives(), "rule__PlayerStatus__Alternatives");
					put(grammarAccess.getFifaAccess().getGroup(), "rule__Fifa__Group__0");
					put(grammarAccess.getFifaAccess().getGroup_3(), "rule__Fifa__Group_3__0");
					put(grammarAccess.getCountryAccess().getGroup(), "rule__Country__Group__0");
					put(grammarAccess.getCountryAccess().getGroup_4(), "rule__Country__Group_4__0");
					put(grammarAccess.getCompetitionAccess().getGroup(), "rule__Competition__Group__0");
					put(grammarAccess.getCompetitionAccess().getGroup_2(), "rule__Competition__Group_2__0");
					put(grammarAccess.getCompetitionAccess().getGroup_8(), "rule__Competition__Group_8__0");
					put(grammarAccess.getTrophyAccess().getGroup(), "rule__Trophy__Group__0");
					put(grammarAccess.getTrophyAccess().getGroup_2(), "rule__Trophy__Group_2__0");
					put(grammarAccess.getTrophyAccess().getGroup_2_3(), "rule__Trophy__Group_2_3__0");
					put(grammarAccess.getTeamAccess().getGroup(), "rule__Team__Group__0");
					put(grammarAccess.getTeamAccess().getGroup_2(), "rule__Team__Group_2__0");
					put(grammarAccess.getTeamAccess().getGroup_5(), "rule__Team__Group_5__0");
					put(grammarAccess.getTeamAccess().getGroup_5_3(), "rule__Team__Group_5_3__0");
					put(grammarAccess.getTeamAccess().getGroup_15(), "rule__Team__Group_15__0");
					put(grammarAccess.getStadiumAccess().getGroup(), "rule__Stadium__Group__0");
					put(grammarAccess.getStadiumAccess().getGroup_3(), "rule__Stadium__Group_3__0");
					put(grammarAccess.getPresidentAccess().getGroup(), "rule__President__Group__0");
					put(grammarAccess.getPresidentAccess().getGroup_4(), "rule__President__Group_4__0");
					put(grammarAccess.getCoachAccess().getGroup(), "rule__Coach__Group__0");
					put(grammarAccess.getCoachAccess().getGroup_4(), "rule__Coach__Group_4__0");
					put(grammarAccess.getCoachAccess().getGroup_5(), "rule__Coach__Group_5__0");
					put(grammarAccess.getCoachAccess().getGroup_6(), "rule__Coach__Group_6__0");
					put(grammarAccess.getPlayerAccess().getGroup(), "rule__Player__Group__0");
					put(grammarAccess.getPlayerAccess().getGroup_4(), "rule__Player__Group_4__0");
					put(grammarAccess.getPlayerAccess().getGroup_5(), "rule__Player__Group_5__0");
					put(grammarAccess.getPlayerAccess().getGroup_6(), "rule__Player__Group_6__0");
					put(grammarAccess.getPlayerAccess().getGroup_7(), "rule__Player__Group_7__0");
					put(grammarAccess.getPlayerAccess().getGroup_8(), "rule__Player__Group_8__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getAgentAccess().getGroup(), "rule__Agent__Group__0");
					put(grammarAccess.getAgentAccess().getGroup_4(), "rule__Agent__Group_4__0");
					put(grammarAccess.getAgentAccess().getGroup_5(), "rule__Agent__Group_5__0");
					put(grammarAccess.getAgentAccess().getGroup_5_3(), "rule__Agent__Group_5_3__0");
					put(grammarAccess.getAgentAccess().getGroup_6(), "rule__Agent__Group_6__0");
					put(grammarAccess.getAgentAccess().getGroup_6_3(), "rule__Agent__Group_6_3__0");
					put(grammarAccess.getFifaAccess().getCountryAssignment_2(), "rule__Fifa__CountryAssignment_2");
					put(grammarAccess.getFifaAccess().getCountryAssignment_3_1(), "rule__Fifa__CountryAssignment_3_1");
					put(grammarAccess.getCountryAccess().getNameAssignment_1(), "rule__Country__NameAssignment_1");
					put(grammarAccess.getCountryAccess().getCompetitionAssignment_3(), "rule__Country__CompetitionAssignment_3");
					put(grammarAccess.getCountryAccess().getCompetitionAssignment_4_1(), "rule__Country__CompetitionAssignment_4_1");
					put(grammarAccess.getCompetitionAccess().getNameAssignment_0(), "rule__Competition__NameAssignment_0");
					put(grammarAccess.getCompetitionAccess().getTypeAssignment_2_1(), "rule__Competition__TypeAssignment_2_1");
					put(grammarAccess.getCompetitionAccess().getTrophyAssignment_4(), "rule__Competition__TrophyAssignment_4");
					put(grammarAccess.getCompetitionAccess().getTeamAssignment_7(), "rule__Competition__TeamAssignment_7");
					put(grammarAccess.getCompetitionAccess().getTeamAssignment_8_1(), "rule__Competition__TeamAssignment_8_1");
					put(grammarAccess.getTrophyAccess().getNameAssignment_0(), "rule__Trophy__NameAssignment_0");
					put(grammarAccess.getTrophyAccess().getTeamAssignment_2_2(), "rule__Trophy__TeamAssignment_2_2");
					put(grammarAccess.getTrophyAccess().getTeamAssignment_2_3_1(), "rule__Trophy__TeamAssignment_2_3_1");
					put(grammarAccess.getTeamAccess().getNameAssignment_0(), "rule__Team__NameAssignment_0");
					put(grammarAccess.getTeamAccess().getTypeAssignment_2_1(), "rule__Team__TypeAssignment_2_1");
					put(grammarAccess.getTeamAccess().getStadiumAssignment_4(), "rule__Team__StadiumAssignment_4");
					put(grammarAccess.getTeamAccess().getTrophyAssignment_5_2(), "rule__Team__TrophyAssignment_5_2");
					put(grammarAccess.getTeamAccess().getTrophyAssignment_5_3_1(), "rule__Team__TrophyAssignment_5_3_1");
					put(grammarAccess.getTeamAccess().getPresidentAssignment_8(), "rule__Team__PresidentAssignment_8");
					put(grammarAccess.getTeamAccess().getCoachAssignment_11(), "rule__Team__CoachAssignment_11");
					put(grammarAccess.getTeamAccess().getPlayerAssignment_14(), "rule__Team__PlayerAssignment_14");
					put(grammarAccess.getTeamAccess().getPlayerAssignment_15_1(), "rule__Team__PlayerAssignment_15_1");
					put(grammarAccess.getStadiumAccess().getNameAssignment_1(), "rule__Stadium__NameAssignment_1");
					put(grammarAccess.getStadiumAccess().getCapacityAssignment_3_1(), "rule__Stadium__CapacityAssignment_3_1");
					put(grammarAccess.getPresidentAccess().getNameAssignment_2(), "rule__President__NameAssignment_2");
					put(grammarAccess.getPresidentAccess().getAgeAssignment_4_1(), "rule__President__AgeAssignment_4_1");
					put(grammarAccess.getCoachAccess().getNameAssignment_2(), "rule__Coach__NameAssignment_2");
					put(grammarAccess.getCoachAccess().getAgeAssignment_4_1(), "rule__Coach__AgeAssignment_4_1");
					put(grammarAccess.getCoachAccess().getContratAssignment_5_1(), "rule__Coach__ContratAssignment_5_1");
					put(grammarAccess.getCoachAccess().getAgentAssignment_6_1(), "rule__Coach__AgentAssignment_6_1");
					put(grammarAccess.getPlayerAccess().getNameAssignment_2(), "rule__Player__NameAssignment_2");
					put(grammarAccess.getPlayerAccess().getAgeAssignment_4_1(), "rule__Player__AgeAssignment_4_1");
					put(grammarAccess.getPlayerAccess().getPositionAssignment_5_1(), "rule__Player__PositionAssignment_5_1");
					put(grammarAccess.getPlayerAccess().getStatusAssignment_6_1(), "rule__Player__StatusAssignment_6_1");
					put(grammarAccess.getPlayerAccess().getContratAssignment_7_1(), "rule__Player__ContratAssignment_7_1");
					put(grammarAccess.getPlayerAccess().getAgentAssignment_8_1(), "rule__Player__AgentAssignment_8_1");
					put(grammarAccess.getAgentAccess().getNameAssignment_2(), "rule__Agent__NameAssignment_2");
					put(grammarAccess.getAgentAccess().getAgeAssignment_4_1(), "rule__Agent__AgeAssignment_4_1");
					put(grammarAccess.getAgentAccess().getPlayerAssignment_5_2(), "rule__Agent__PlayerAssignment_5_2");
					put(grammarAccess.getAgentAccess().getPlayerAssignment_5_3_1(), "rule__Agent__PlayerAssignment_5_3_1");
					put(grammarAccess.getAgentAccess().getCoachAssignment_6_2(), "rule__Agent__CoachAssignment_6_2");
					put(grammarAccess.getAgentAccess().getCoachAssignment_6_3_1(), "rule__Agent__CoachAssignment_6_3_1");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public XTextGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(XTextGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
